version: '3.1'

services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    restart: always
    ports:
    - 5173:80
