version: '3.1'

services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_USER: '${DOCKER_MYSQL_USER}'
      MYSQL_ROOT_PASSWORD: '${DOCKER_MYSQL_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${DOCKER_MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${DOCKER_MYSQL_DATABASE}'
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
